### PR TITLE
add verify tx timestamp check

### LINKED ISSUE #27: Check timestamps on getRawTx return values, find an appropriate one and add a security check on verifyPaymentInfo
Blocktime, time or timereceived should be good candidates.
If the timestamp is older than 1h the node should not confirm the tx.

### PR DESCRIPTION
**Pull request by Bitcoinera**
Closes #27

### CODE REVIEW

**Comment by jamiemadrox779** [comment]
Please move this check out of getRawTx and to main.js, getRawTx is a generic method and should work also for other purposes

**Comment by Bitcoinera** [comment]
> Please move this check out of getRawTx and move it to main.js

All good now. Also made it much better without the error but returning false :+1:

**Review by jamiemadrox779 — COMMENTED** [review]
yes now it is good. But I think utils would be the perfect place

**Comment by Bitcoinera** [comment]
> yes now it is good. But I think utils would be the perfect place

Done!

**Comment by jamiemadrox779** [comment]
Already solved

**Pull request closed without merging**
