### PR TITLE
Fix confirmation delays

### PR DESCRIPTION
**Pull request by ztane**
The confirmation node stores the id of the latest transaction that has been processed (or given up on!) into the db for faster syncing after if the process crashes.

### CODE REVIEW

**Review by jamiemadrox779 — CHANGES_REQUESTED** [review]
Why create a new table last_processed_txid if we have already payments?

**Comment by jamiemadrox779** [comment]
Missing tests

**Comment by ztane** [comment]
> Why create a new table last_processed_txid if we have already payments?

Well, there is not necessarily a reason for that *after* the payments is re-enabled. The idea was that the `from` index state would be persisted in this and need not be scanned from the contract.

**Comment by jamiemadrox779** [comment]
> > Why create a new table last_processed_txid if we have already payments?
> 
> Well, there is not necessarily a reason for that _after_ the payments is re-enabled. The idea was that the `from` index state would be persisted in this and need not be scanned from the contract.

Then lets use the payments table please

**Pull request merged**
